import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@locospace/ui/src/app/globals.css'

const inter = Inter({ subsets: ['latin'] })

import { ApolloProvider } from '@locospace/network/src/config/apollo'
import { SessionProvider } from '@locospace/ui/src/components/molecules/SessionProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Header } from '@locospace/ui/src/components/organisms/Header'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body className={inter.className}>
            <Header menuItems={[]} />
            {children}
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  )
}
